[package]
name = "weechat-matrix"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "ISC"
resolver = "2"

[lib]
name = "matrix"
crate-type = ["cdylib"]

[features]
default = []

[dependencies]
anyhow = "1.0.41"
clap = "2.33.3"
chrono = "0.4.19"
dashmap = "5.3.3"
futures = "0.3.21"
indoc = "1.0.6"
url = "2.2.2"
qrcode = { version = "0.12.0", default-features = false }
serde_json = "1.0.81"
strum = "0.20.0"
strum_macros = "0.20.0"
syntect = "5.0.0"
tokio = { version = "1.18.2", features = ["rt-multi-thread", "sync"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
uuid = { version = "1.0.0", features = ["v4"] }
unicode-segmentation = "1.9.0"

[dependencies.weechat]
git = "https://github.com/poljar/rust-weechat"
features = ["async", "config_macro"]

[dependencies.matrix-sdk]
path = "../../matrix/matrix-rust-sdk/crates/matrix-sdk/"
# rev = "4971802e7506dd56f78be6d24e373282133b31cd"
features = ["markdown", "qrcode"]

[profile.dev.package]
quote = { opt-level = 2 }
sha2 = { opt-level = 2 }
