[package]
name = "weechat-matrix"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "ISC"
resolver = "2"

[lib]
name = "matrix"
crate-type = ["cdylib"]

[features]
default = []

[dependencies]
url = "2.2.1"
futures = "0.3.14"
tokio = { version = "1.4.0", features = [ "rt-multi-thread", "sync" ] }
dashmap = "4.0.2"

tracing = "0.1.25"
tracing-subscriber = "0.2.16"

clap = "2.33.3"
syntect = "4.5.0"
uuid = { version = "0.8.2", features = ["v4"] }
indoc = "1.0.3"
unicode-segmentation = "1.7.1"
strum = "0.20.0"
strum_macros = "0.20.1"
chrono = "0.4.19"
serde_json = "1.0.64"

[dependencies.weechat]
git = "https://github.com/poljar/rust-weechat"
features = ["async", "config_macro"]

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk"
features = ["markdown"]
