on: [push]

name: build-test-release

jobs:
  x86_64_glibc:
    name: Ubuntu 18.04 (glibc)
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Install latest-stable weechat for Ubuntu 18.04
        run: |
          sudo apt update
          sudo apt install dirmngr gpg-agent apt-transport-https
          sudo apt-key adv --keyserver hkps://keys.openpgp.org --recv-keys 11E9DE8848F2B65222AA75B8D1820DB22A11534E
          echo "deb https://weechat.org/ubuntu bionic main" | sudo tee /etc/apt/sources.list.d/weechat.list
          echo "deb-src https://weechat.org/ubuntu bionic main" | sudo tee -a /etc/apt/sources.list.d/weechat.list
          sudo apt update
          sudo apt install weechat-curses weechat-plugins weechat-python weechat-perl weechat-dev
          echo "version of weechat-plugin.h that weechat-sys uses by default:"
          grep -m 1 -n -H "WEECHAT_PLUGIN_API_VERSION" "/usr/include/weechat/weechat-plugin.h"

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: 'weechat-matrix-rs-x86_64-unknown-linux-gnu'
          path: target/release/libmatrix.so
