on: [push]

name: build-test-release

jobs:
  x86_64_glibc:
    name: Ubuntu 18.04 (glibc)
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: 'weechat-matrix-rs-x86_64-unknown-linux-gnu'
          path: target/release/weechat-matrix-rs
